export const ALL_CLASS_REQUEST = "ALL_CLASS_REQUEST";
export const ALL_CLASS_SUCCESS = "ALL_CLASS_SUCCESS";
export const ALL_CLASS_FAIL = "ALL_CLASS_FAIL";

export const NEW_CLASS_REQUEST = "NEW_CLASS_REQUEST";
export const NEW_CLASS_SUCCESS = "NEW_CLASS_SUCCESS";
export const NEW_CLASS_RESET = "NEW_CLASS_RESET";
export const NEW_CLASS_FAIL = "NEW_CLASS_FAIL";

export const CLASS_DETAILS_REQUEST = "CLASS_DETAILS_REQUEST";
export const CLASS_DETAILS_SUCCESS = "CLASS_DETAILS_SUCCESS";
export const CLASS_DETAILS_FAIL = "CLASS_DETAILS_FAIL";

export const DELETE_CLASS_REQUEST = "DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";
export const DELETE_CLASS_RESET = "DELETE_CLASS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERROR";


