export const ALL_COURSES_REQUEST = "ALL_COURSES_REQUEST";
export const ALL_COURSES_SUCCESS = "ALL_COURSES_SUCCESS";
export const ALL_COURSES_FAIL = "ALL_COURSES_FAIL";

export const NEW_COURSES_REQUEST = "NEW_COURSES_REQUEST";
export const NEW_COURSES_SUCCESS = "NEW_COURSES_SUCCESS";
export const NEW_COURSES_RESET = "NEW_COURSES_RESET";
export const NEW_COURSES_FAIL = "NEW_COURSES_FAIL";

export const COURSES_DETAILS_REQUEST = "COURSES_DETAILS_REQUEST";
export const COURSES_DETAILS_SUCCESS = "COURSES_DETAILS_SUCCESS";
export const COURSES_DETAILS_FAIL = "COURSES_DETAILS_FAIL";

export const DELETE_COURSES_REQUEST = "DELETE_COURSES_REQUEST";
export const DELETE_COURSES_SUCCESS = "DELETE_COURSES_SUCCESS";
export const DELETE_COURSES_FAIL = "DELETE_COURSES_FAIL";
export const DELETE_COURSES_RESET = "DELETE_COURSES_RESET";

export const ALL_CALANDER_REQUEST = "ALL_CALANDER_REQUEST";
export const ALL_CALANDER_SUCCESS = "ALL_CALANDER_SUCCESS";
export const ALL_CALANDER_FAIL = "ALL_CALANDER_FAIL";

export const ALL_CALANDER2_REQUEST = "ALL_CALANDER2_REQUEST";
export const ALL_CALANDER2_SUCCESS = "ALL_CALANDER2_SUCCESS";
export const ALL_CALANDER2_FAIL = "ALL_CALANDER2_FAIL";

export const NEW_CALANDER_REQUEST = "NEW_CALANDER_REQUEST";
export const NEW_CALANDER_SUCCESS = "New_CALANDER_SUCCESS";
export const NEW_CALANDER_FAIL = "New_CALANDER_FAIL";
export const NEW_CALANDER_RESET = "NEW_CALANDER_RESET";

export const TOPIC_DETAILS_REQUEST = "TOPIC_DETAILS_REQUEST";
export const TOPIC_DETAILS_SUCCESS = "TOPIC_DETAILS_SUCCESS";
export const TOPIC_DETAILS_FAIL = "TOPIC_DETAILS_FAIL";

export const TOPICS_DETAILS_REQUEST = "TOPICS_DETAILS_REQUEST";
export const TOPICS_DETAILS_SUCCESS = "TOPICS_DETAILS_SUCCESS";
export const TOPICS_DETAILS_FAIL = "TOPICS_DETAILS_FAIL";

export const NEW_COURSESS_REQUEST = "NEW_COURSESS_REQUEST";
export const NEW_COURSESS_SUCCESS = "NEW_COURSESS_SUCCESS";
export const NEW_COURSESS_FAIL = "NEW_COURSESS_FAIL";
export const NEW_COURSESS_RESET = "NEW_COURSESS_RESET"

export const CLEAR_ERRORS = "CLEAR_ERROR";

